// app/layout.tsx

import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css'

import { CartProvider } from '@/contexts/CartContext'; // import CartProvider

const beVietnam = Be_Vietnam_Pro({
  subsets: ['vietnamese'],
  weight: ['400', '500', '700'],
  variable: '--font-be-vietnam',
});

export const metadata: Metadata = {
  title: 'Anima Project - Automatically generated by Anima',
  description: 'A Next.js project automatically generated by Anima using the Shadcn UI library',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={beVietnam.className}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
